language: python
# We don't need sudo... this might speed up builds
sudo: false
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=cover
install:
  - travis_retry pip install tox
script:
  - travis_retry tox
