language: python
# We don't need sudo... this might speed up builds
sudo: false
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=cover
install:
  - pip install tox
script:
  - tox
